<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
	  <PackageIcon>Icon.png</PackageIcon>
	  <ApplicationIcon>Images\Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\ViewerWindow.xaml - Copia.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Views\ViewerWindow - Copia.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Icon.ico" />
    <Resource Include="Images\Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.13.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Images\Icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
